# vim:ft=ansible
---
- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.local
    - ~/.local/bin

- name: install deps
  apt:
    name: python-docker
    state: latest
  become: yes

- name: clone dockerfiles
  git:
    repo: https://github.com/xsteadfastx/dockerfiles.git
    dest: ~/.dockerfiles

- name: build image
  docker_image:
    name: weechat
    path: ~/.dockerfiles/weechat

- name: link files
  file:
    src={{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - { 'src': '{{ batcave_path }}/roles/weechat/files/config', 'dest': '~/.weechat' }
    - { 'src': '{{ batcave_path }}/roles/weechat/files/weechat', 'dest': '~/.local/bin/weechat' }

- name: create files
  template:
    src={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - { 'src': 'relay.conf.j2', 'dest': '~/.weechat/relay.conf' }

- name: add relay passphrase file
  lineinfile:
    dest=~/.weechat-passphrase
    line={{ weechat_passphrase }}
    state=present
    create=yes
    mode=600
