---
- name: install deps
  apt:
    name=weechat
    state=latest
  become: yes
  when: ansible_os_family == 'Debian'

- name: install deps
  apt:
    name=weechat
    state=latest
  become: yes
  when: ansible_os_family == 'Alpine'

- name: link files
  file:
    src={{ batcave_path }}/roles/weechat/files
    dest=~/.weechat
    state=link

- name: create files
  template:
    src={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - { 'src': 'relay.conf.j2', 'dest': '~/.weechat/relay.conf' }

- name: add relay passphrase file
  lineinfile:
    dest=~/.weechat-passphrase
    line={{ weechat_passphrase }}
    state=present
    create=yes
    mode=600
