# vim:ft=ansible
---
- name: uninstall unclutter
  apt:
    name: unclutter
    state: absent
  become: yes
  when: ansible_os_family == "Debian"

- name: debian | install deps
  apt:
    state: latest
    name:
      - libev-dev
      - libxi-dev
  become: true
  when: ansible_os_family == "Debian"

- name: alpine | install deps
  apk:
    name:
      - unclutter-xfixes
  become: true
  when: ansible_os_family == "Alpine"

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.local/
    - ~/.local/bin
    - ~/src

- name: clone unclutter
  git:
    repo: https://github.com/Airblader/unclutter-xfixes.git
    dest: ~/src/unclutter
  when: ansible_os_family == "Debian"

- name: compile
  command: make unclutter
  args:
    chdir: ~/src/unclutter
  when: ansible_os_family == "Debian"

- name: debian | link unclutter
  file:
    src=~/src/unclutter/unclutter
    dest=~/.local/bin/unclutter
    state=link
  when: ansible_os_family == "Debian"

- name: alpine | link unclutter
  file:
    src=/usr/bin/unclutter-xfixes
    dest=~/.local/bin/unclutter
    state=link
  when: ansible_os_family == "Alpine"
