# vim:ft=ansible
---
- name: uninstall unclutter
  apt:
    name: unclutter
    state: absent
  become: yes

- name: install deps
  apt:
    state: latest
    name:
      - libev-dev
      - libxi-dev
  become: true
  tags:
    - skip_ansible_lint

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.local/
    - ~/.local/bin
    - ~/src

- name: clone unclutter
  git:
    repo: https://github.com/Airblader/unclutter-xfixes.git
    dest: ~/src/unclutter
  tags:
    - skip_ansible_lint

- name: compile
  command: make unclutter
  args:
    chdir: ~/src/unclutter
  tags:
    - skip_ansible_lint

- name: link unclutter
  file:
    src=~/src/unclutter/unclutter
    dest=~/.local/bin/unclutter
    state=link
