# vim:filetype=ansible
---
- name: install firefox
  apt:
    name=firefox
  become: yes

- name: open addon install pages
  command: firefox {{ item }}
  with_items:
    - https://addons.mozilla.org/de/firefox/addon/microfox-for-firefox/
    - https://addons.mozilla.org/de/firefox/addon/vimfx/
    - https://addons.mozilla.org/de/firefox/addon/ublock-origin/
