# vim:ft=ansible
---
- name: add ppa
  apt_repository:
    repo: 'ppa:fish-shell/release-2'
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: install deps
  package:
    name={{ item }}
    state=latest
  with_items:
    - fish
    - git
  become: yes

- name: install deps debian
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - ncurses-base
  become: yes
  when: ansible_os_family == 'Debian'

- name: install deps alpine
  apk:
    name: "{{ item }}"
    state: latest
  with_items:
    - bc
    - ncurses
  become: yes
  when: ansible_os_family == 'Alpine'

- name: remove files
  file:
    path={{ item }}
    state=absent
  with_items:
    - ~/.config/fish
    - ~/.config/omf
    - ~/.local/share/omf

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.config
    - ~/.config/fish
    - ~/.config/fish/completions
    - ~/.config/fish/conf.d
    - ~/.config/fish/functions
    #- ~/.config/omf

- name: link files
  file:
    src={{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    # config
    - {'src': '{{ batcave_path }}/roles/fish/files/config.fish', 'dest': '~/.config/fish/config.fish'}
  # oh-my-fish
    #- {'src': '{{ batcave_path }}/roles/fish/files/omf/bundle', 'dest': '~/.config/omf/bundle'}
    #- {'src': '{{ batcave_path }}/roles/fish/files/omf/channel', 'dest': '~/.config/omf/channel'}
    #- {'src': '{{ batcave_path }}/roles/fish/files/omf/theme', 'dest': '~/.config/omf/theme'}

- name: get files
  get_url:
    url={{ item.src }}
    dest={{ item.dest }}
  with_items:
    # theme
    - {'src': 'https://raw.githubusercontent.com/davewongillies/theme-bobthefish/master/fish_greeting.fish', 'dest': '~/.config/fish/functions/fish_greeting.fish'}
    - {'src': 'https://raw.githubusercontent.com/davewongillies/theme-bobthefish/master/fish_mode_prompt.fish', 'dest': '~/.config/fish/functions/fish_mode_prompt.fish'}
    - {'src': 'https://raw.githubusercontent.com/davewongillies/theme-bobthefish/master/fish_prompt.fish', 'dest': '~/.config/fish/functions/fish_prompt.fish'}
    - {'src': 'https://raw.githubusercontent.com/davewongillies/theme-bobthefish/master/fish_right_prompt.fish', 'dest': '~/.config/fish/functions/fish_right_prompt.fish'}
    - {'src': 'https://raw.githubusercontent.com/davewongillies/theme-bobthefish/master/fish_title.fish', 'dest': '~/.config/fish/functions/fish_title.fish'}
    # completions
    - {'src': 'https://raw.githubusercontent.com/barnybug-archive/docker-fish-completion/master/docker-compose.fish', 'dest': '~/.config/fish/completions/docker-compose.fish'}

- name: set shell
  user:
    name={{ ansible_env.USER }}
    shell=/usr/bin/fish
  become: yes
  when: ansible_os_family == 'Debian'
