# vim:ft=ansible
---
- name: set st version
  set_fact: st_version="0.8.1"

- name: install deps
  apt:
    name={{ item }}
    state=latest
  with_items:
    - libx11-dev
    - libxext-dev
    - libxft-dev
  become: yes

- name: create dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - /tmp/st
    - ~/.local/bin

- name: get st
  unarchive:
    src: 'http://dl.suckless.org/st/st-{{ st_version }}.tar.gz'
    dest: '/tmp/st'
    remote_src: yes

- name: get some files
  get_url:
    url: "{{ item.src }}"
    dest: /tmp/st/st-{{ st_version }}/{{ item.dest }}
  with_items:
    - { 'src': 'http://st.suckless.org/patches/solarized/st-no_bold_colors-{{ st_version }}.diff', 'dest': 'no_bold_colors.diff' }

- name: patch st
  patch:
    src: /tmp/st/st-{{ st_version }}/{{ item }}
    basedir: /tmp/st/st-{{ st_version }}
    strip: 1
  with_items:
    - no_bold_colors.diff

- name: copy config
  copy:
    src: config.def.h
    dest: /tmp/st/st-{{ st_version }}/config.h

- name: compile st
  command: make
  args:
    chdir: /tmp/st/st-{{ st_version }}

- name: copy st
  copy:
    src: /tmp/st/st-{{ st_version }}/st
    dest: ~/.local/bin/st
    mode: 0775

- name: remove tmp dir
  file:
    path=/tmp/st
    state=absent
