# vim:ft=ansible
---
- name: install deps
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - isync
    - msmtp
    - mutt
    - notmuch
    - notmuch-mutt
  tags:
    - skip_ansible_lint

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.mutt

- name: link files
  file:
    src={{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - {'src': '{{ batcave_path }}/roles/mutt/files/gmail', 'dest': '~/.mutt/gmail'}
    - {'src': '{{ batcave_path }}/roles/mutt/files/gpg', 'dest': '~/.mutt/gpg'}
    - {'src': '{{ batcave_path }}/roles/mutt/files/muttrc', 'dest': '~/.mutt/muttrc'}
    - {'src': '{{ batcave_path }}/roles/mutt/files/notmuch-config', 'dest': '~/.notmuch-config'}
    - {'src': '{{ batcave_path }}/roles/mutt/files/smime', 'dest': '~/.mutt/smime'}
    - {'src': '{{ batcave_path }}/roles/mutt/files/dracula', 'dest': '~/.mutt/dracula'}

- name: create files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
  with_items:
    - {'src': 'mbsyncrc.j2', 'dest': '~/.mbsyncrc'}
    - {'src': 'msmtprc.j2', 'dest': '~/.msmtprc'}

- name: link systemd files
  file:
    src={{ item.src }}
    dest={{ item.dest }}
    state=link
  become: yes
  with_items:
    - {'src': '/home/{{ ansible_user_id }}/.batcave/roles/mutt/files/mbsync.service', 'dest': '/etc/systemd/system/mbsync.service'}
    - {'src': '/home/{{ ansible_user_id }}/.batcave/roles/mutt/files/mbsync.timer', 'dest': '/etc/systemd/system/mbsync.timer'}
