---
- name: install deps
  apt:
    name:
      - qemu-kvm
      - qemu-system-x86
      - spice-client-gtk
  become: true

- name: needed dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.local
    - ~/.local/bin

- name: link files
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - {'src': '{{ batcave_path }}/roles/kvm/files/boot-alpine', 'dest': '~/.local/bin/boot-alpine'}
    - {'src': '{{ batcave_path }}/roles/kvm/files/boot-windows', 'dest': '~/.local/bin/boot-windows'}
