---
- name: clone
  git:
    repo: https://github.com/xsteadfastx/batcave.git
    dest: ~/.batcave
  when: '"localhost" not in group_names'

- name: debian | update apt cache
  apt:
    update_cached: true
  become: true
  when: ansible_os_family == 'Debian'

- name: alpine | update apk cache
  apk:
    update_cache: true
  become: true
  when: ansible_os_family == 'Alpine'

- stat:
    path: ~/.nix-env/bin/nix
    register: nix_stat

- name: nix | update nix cache
  nix:
    update_cache: true
  when: nix_stat.stat.exists
