# vim:ft=ansible
---
- name: clone
  git:
    repo=https://github.com/xsteadfastx/batcave.git
    dest=~/.batcave
  when: '"localhost" not in group_names'

- name: update apt cache
  apt: update_cache=yes
  become: yes
  when: ansible_os_family == 'Debian'
