# vim:ft=ansible
---
- name: clone
  git:
    repo=https://github.com/xsteadfastx/batcave.git
    dest=~/.batcave
  when: '"localhost" not in group_names'
  tags:
    - skip_ansible_lint

- name: debian | update apt cache
  apt: update_cache=yes
  become: yes
  when: ansible_os_family == 'Debian'

- name: alpine | update apk cache
  apk: update_cache=yes
  become: yes
  when: ansible_os_family == 'Alpine'
