repos:
  - repo: https://github.com/willthames/ansible-lint.git
    rev: v3.5.0rc1
    hooks:
      - id: ansible-lint
  - repo: https://github.com/IamTheFij/ansible-pre-commit.git
    rev: v0.1.2
    hooks:
      - id: encryption-check
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v1.3.0
    hooks:
      - id: check-yaml
  - repo: https://github.com/Lucas-C/pre-commit-hooks-go
    rev: v1.0.0
    hooks:
      - id: checkmake
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.10.0
    hooks:
      - id: gitlint
        stages: [commit-msg]
  - repo: https://github.com/Yelp/detect-secrets
    rev: 0.10.1
    hooks:
      - id: detect-secrets
