---
- name: debian | install deps
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - adwaita-qt
    - adwaita-icon-theme-full
    - fonts-symbola
  become: true
  when: ansible_os_family == 'Debian'

- name: alpine | install deps
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - adwaita-gtk2-them
    - adwaita-icon-them
  become: true
  when: ansible_os_family == 'Alpine'

- name: needed dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.config
    - ~/.config/fontconfig
    - ~/.config/gtk-3.0
    - ~/.fonts
    - ~/.themes

- name: link files
  file:
    src: "{{ batcave_path }}/roles/xresources/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - {'src': 'Fura Mono Regular Nerd Font Complete Mono.otf', 'dest': '~/.fonts/Fura Mono Regular Nerd Font Complete Mono.otf'}
    - {'src': 'settings.ini', 'dest': '~/.config/gtk-3.0/settings.ini'}
    - {'src': 'gtkrc-2.0', 'dest': '~/.gtkrc-2.0'}
    # - {'src': 'fonts.conf', 'dest': '~/.config/fontconfig/fonts.conf'}

- name: install theme
  unarchive:
    src: "{{ batcave_path }}/roles/xresources/files/Ant-Dracula.tar"
    dest: ~/.themes

- name: rebuild font cache
  command: fc-cache -r ~/.fonts
