---
- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.fonts

- name: remove files
  file:
    path={{ item }}
    state=absent
  with_items:
    - ~/.Xresources
    - ~/.xprofile
    - ~/.fonts/RobotoMono-Regular.ttf

- name: link files
  file:
    src={{ role_path }}/files/{{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - {'src': 'xresources', 'dest': '~/.Xresources'}
    - {'src': 'xprofile', 'dest': '~/.xprofile'}
    - {'src': 'RobotoMono-Regular.ttf', 'dest': '~/.fonts/RobotoMono-Regular.ttf'}
