# vim:ft=ansible
---
- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.fonts

- name: remove files
  file:
    path={{ item }}
    state=absent
  with_items:
    - ~/.Xresources
    - ~/.xprofile
    - ~/.fonts/RobotoMono-Regular.ttf
    - ~/.fonts/Monoisome-Regular.ttf
    - ~/.fonts/FiraCode-Regular.ttf

- name: link files
  file:
    src={{ batcave_path }}/roles/xresources/files/{{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - {'src': 'xresources', 'dest': '~/.Xresources'}
    - {'src': 'xprofile', 'dest': '~/.xprofile'}
    - {'src': 'FiraCode-Regular.ttf', 'dest': '~/.fonts/FiraCode-Regular.ttf'}

- name: rebuild font cache
  command: fc-cache -r ~/.fonts
