---
- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.fonts

- name: copy files
  copy:
    src={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - {'src': 'xresources', 'dest': '~/.Xresources'}
    - {'src': 'xprofile', 'dest': '~/.xprofile'}
    - {'src': 'RobotoMono-Regular.ttf', 'dest': '~/.fonts/RobotoMono-Regular.ttf'}
