---
- name: install deps
  package:
    name={{ item }}
    state=latest
  with_items:
    - adwaita-qt
    - fonts-symbola
  become: yes
  when: ansible_os_family == 'Debian'
  tags:
    - skip_ansible_lint

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.config
    - ~/.config/fontconfig
    - ~/.config/gtk-3.0
    - ~/.fonts
    - ~/.themes

- name: link files
  file:
    src={{ batcave_path }}/roles/xresources/files/{{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - {'src': 'Roboto Mono Nerd Font Complete.ttf', 'dest': '~/.fonts/Roboto Mono Nerd Font Complete.ttf'}
    - {'src': 'settings.ini', 'dest': '~/.config/gtk-3.0/settings.ini'}
    - {'src': 'gtkrc-2.0', 'dest': '~/.gtkrc-2.0'}
    # - {'src': 'fonts.conf', 'dest': '~/.config/fontconfig/fonts.conf'}

- name: install theme
  unarchive:
    src: "{{ batcave_path }}/roles/xresources/files/Ant-Dracula.tar"
    dest: ~/.themes

- name: rebuild font cache
  command: fc-cache -r ~/.fonts
  tags:
    - skip_ansible_lint
