# vim:ft=ansible
---
- name: install deps
  package:
    name=fonts-symbola
    state=latest
  become: yes
  when: ansible_os_family == 'Debian'

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.fonts

- name: remove files
  file:
    path={{ item }}
    state=absent
  with_items:
    - ~/.Xresources
    - ~/.xprofile
    - ~/.fonts/RobotoMono-Regular.ttf
    - ~/.fonts/Monoisome-Regular.ttf
    - ~/.fonts/FiraCode-Regular.ttf
    - ~/.fonts/FiraMono-Regular.ttf
    - ~/.fonts/Hack-Regular.ttf

- name: link files
  file:
    src={{ batcave_path }}/roles/xresources/files/{{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - {'src': 'FiraMono-Regular.ttf', 'dest': '~/.fonts/FiraMono-Regular.ttf'}

- name: rebuild font cache
  command: fc-cache -r ~/.fonts
