# vim:ft=ansible
---
- name: set st version
  set_fact: st_version="0.8.3"

- name: install deps
  package:
    state: latest
    name:
      - libx11-dev
      - libxext-dev
      - libxft-dev
      - libharfbuzz-icu0
      - libharfbuzz0b
  become: yes
  tags:
    - skip_ansible_lint

- name: create dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - /tmp/st
    - ~/.local/bin

- name: get st
  unarchive:
    src: 'http://dl.suckless.org/st/st-{{ st_version }}.tar.gz'
    dest: '/tmp/st'
    remote_src: yes

- name: copy config
  copy:
    src: config.def.h
    dest: /tmp/st/st-{{ st_version }}/config.h

- name: patch
  shell: patch < {{ role_path }}/files/st-ligatures-20200430-0.8.3.diff
  args:
    chdir: /tmp/st/st-{{ st_version }}

- name: compile st
  command: make
  args:
    chdir: /tmp/st/st-{{ st_version }}
  tags:
    - skip_ansible_lint

- name: copy st
  copy:
    src: /tmp/st/st-{{ st_version }}/st
    dest: ~/.local/bin/st
    mode: 0775

- name: remove old terminfo
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob: ~/.terminfo/s/st*

- name: install new terminfo
  command: /usr/bin/tic -sx st.info
  args:
    chdir: /tmp/st/st-{{ st_version }}
  tags:
    - skip_ansible_lint

- name: remove tmp dir
  file:
    path=/tmp/st
    state=absent
