---
- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.config
    - ~/.config/qutebrowser
    - ~/.local
    - ~/.local/bin
    - ~/.local/share
    - ~/.local/share/qutebrowser
    - ~/src

- name: check if newer ubuntu version
  set_fact:
    fallback: "{% if ansible_distribution_version|float < 17.04 %}true{% else %}false{% endif %}"

- name: install deps
  apt:
    name:
      - qutebrowser
      - tldextract
  become: yes
  when: not fallback

- name: clone qutebrowser repo
  git:
    repo: https://github.com/qutebrowser/qutebrowser.git
    dest: ~/src/qutebrowser
  when: fallback

- name: install
  command: tox -e mkvenv-pypi
  args:
    chdir: ~/src/qutebrowser
  when: fallback

- name: link start script
  file:
    src={{ batcave_path }}/roles/qutebrowser/files/qutebrowser
    dest=~/.local/bin/qutebrowser
    state=link
  when: fallback

- name: link config
  file:
    src={{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - { 'src': '{{ batcave_path }}/roles/qutebrowser/files/config.py', 'dest': '~/.config/qutebrowser/config.py' }

- name: get dracula
  git:
    repo: https://github.com/evannagle/qutebrowser-dracula-theme.git
    dest: ~/.config/qutebrowser/dracula

- name: install mpv
  apt:
    name: mpv
    state: latest
  become: yes
