# vim:filetype=ansible
---
- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.config
    - ~/.config/qutebrowser
    - ~/.local
    - ~/.local/bin
    - ~/.local/share
    - ~/.local/share/qutebrowser

- name: get files
  get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {'src': 'https://qutebrowser.org/python3-pypeg2_2.15.2-1_all.deb', 'dest': '/tmp/pypeg2.deb'}
    - {'src': 'https://github.com/qutebrowser/qutebrowser/releases/download/v1.0.4/qutebrowser_1.0.4-1_all.deb', 'dest': '/tmp/qutebrowser.deb'}

- name: install deps
  apt:
    deb: "{{ item }}"
  become: yes
  with_items:
    - /tmp/pypeg2.deb
    - /tmp/qutebrowser.deb

- name: link files
  file:
    src={{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - { 'src': '{{ batcave_path }}/roles/qutebrowser/files/qutebrowser', 'dest': '~/.local/bin/qutebrowser' }
    - { 'src': '{{ batcave_path }}/roles/qutebrowser/files/config.py', 'dest': '~/.config/qutebrowser/config.py' }

- name: remove files
  file:
    path={{ item }}
    state=absent
  with_items:
    - /tmp/pypeg2.deb
    - /tmp/qutebrowser.deb
