---
- name: install deps
  apt:
    name:
      - python3
      - python3-pip
  become: true

- name: clone bumblebee
  git:
    repo: https://github.com/tobi-wan-kenobi/bumblebee-status.git
    dest: /opt/bumblee-status
  become: true

- name: virtualenv
  pip:
    name:
      - requests
      - psutil
      - netifaces
    virtualenv: /opt/bumblee-status/env
    virtualenv_python: /usr/bin/python3
  become: true
