# vim:filetype=ansible
---
- name: install firefox
  apt:
    name=firefox
    state=latest
  become: yes
  tags:
    - skip_ansible_lint

- name: open addon install pages
  command: firefox {{ item }}
  with_items:
    - https://addons.mozilla.org/en-US/firefox/addon/dracula-dark-colorscheme/
    - https://addons.mozilla.org/de/firefox/addon/ublock-origin/
    - https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/
  tags:
    - skip_ansible_lint
