# vim:ft=ansible
---
- name: install deps
  apt:
    name={{ item }}
    state=present
  with_items:
    - curl
    - python3-venv
  become: yes

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.local
    - ~/.local/bin

- name: install pipsi
  shell:
    curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | /usr/bin/python3
    args:
      creates: ~/.local/venvs/pipsi/bin/pipsi
