# vim:ft=ansible
---
- name: install deps
  package:
    name=zsh
    state=present
  become: yes

- name: clone antigen
  git:
    repo=https://github.com/zsh-users/antigen.git
    dest=~/.antigen

- name: link files
  file:
    src={{ batcave_path }}/roles/zsh/files/{{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - {'src': 'zshrc', 'dest': '~/.zshrc'}

- name: set shell
  user:
    name={{ ansible_env.USER }}
    shell=/usr/bin/zsh
  become: yes
  when: ansible_os_family == 'Debian'

- name: set shell
  replace:
    dest=/etc/passwd
    regexp='(^vagrant:.+:.+:.+:.+:.+:).+$'
    replace='\1/bin/zsh'
  become: yes
  when: ansible_os_family == 'Alpine' and ansible_user_id == 'vagrant' and ansible_user_shell != '/usr/bin/zsh'
