---
- name: install deps
  apt:
    name=zsh
    state=present
  become: yes
  when: ansible_os_family == 'Debian'

- name: install deps
  apk:
    name=zsh
    state=present
  become: yes
  when: ansible_os_family == 'Alpine'

- name: remove prezto dir for fresh clone
  file:
    path=~/.zprezto
    state=absent

- name: clone prezto
  git:
    repo=https://github.com/sorin-ionescu/prezto.git
    dest=~/.zprezto

- name: link prezto files
  file:
    src={{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - { 'src': '~/.zprezto/runcoms/zlogin', 'dest': '~/.zlogin' }
    - { 'src': '~/.zprezto/runcoms/zlogout', 'dest': '~/.zlogout' }
    - { 'src': '~/.zprezto/runcoms/zshenv', 'dest': '~/.zshenv' }

- name: remove files
  file:
    path={{ item }}
    state=absent
  with_items:
    - ~/.zshrc
    - ~/.zpreztorc
    - ~/.zprofile

- name: link files
  file:
    src={{ batcave_path }}/roles/zsh/files/{{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - {'src': 'zshrc', 'dest': '~/.zshrc'}
    - {'src': 'zpreztorc', 'dest': '~/.zpreztorc'}
    - {'src': 'zprofile', 'dest': '~/.zprofile'}

- name: set shell
  user:
    name={{ ansible_env.USER }}
    shell=/usr/bin/zsh
  become: yes
  when: ansible_os_family == 'Debian'

- name: set shell
  replace:
    dest=/etc/passwd
    regexp='(^vagrant:.+:.+:.+:.+:.+:).+$'
    replace='\1/bin/zsh'
  become: yes
  when: ansible_os_family == 'Alpine' and ansible_user_id == 'vagrant' and ansible_user_shell != '/usr/bin/zsh'
