---
- name: install deps
  apt:
    name=zsh
    state=present
  become: yes
  when: ansible_os_family == 'Debian'

- name: install deps
  apk:
    name=zsh
    state=present
  become: yes
  when: ansible_os_family == 'Alpine'

- name: clone prezto
  git:
    repo=https://github.com/sorin-ionescu/prezto.git
    dest=~/.zprezto

- name: link prezto files
  file:
    src={{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - { 'src': '~/.zprezto/runcoms/zlogin', 'dest': '~/.zlogin' }
    - { 'src': '~/.zprezto/runcoms/zlogout', 'dest': '~/.zlogout' }
    - { 'src': '~/.zprezto/runcoms/zprofile', 'dest': '~/.zprofile' }
    - { 'src': '~/.zprezto/runcoms/zshenv', 'dest': '~/.zshenv' }

- name: copy files
  copy:
    src={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - {'src': 'zshrc', 'dest': '~/.zshrc'}
    - {'src': 'bash_aliases', 'dest': '~/.bash_aliases'}
    - {'src': 'zpreztorc', 'dest': '~/.zpreztorc'}

- name: set shell
  user:
    name={{ ansible_env.USER }}
    shell=/usr/bin/zsh
  become: yes
  when: ansible_os_family == 'Debian'

- name: set shell
  replace:
    dest=/etc/passwd
    regexp='(^vagrant:.+:.+:.+:.+:.+:).+$'
    replace='\1/bin/zsh'
  become: yes
  when: ansible_os_family == 'Alpine' and ansible_user_id == 'vagrant' and ansible_user_shell != '/usr/bin/zsh'
