---
- stat:
    path: ~/.nix-profile/bin/nix
  register: nix_stat

- name: check if nix is installed
  set_fact:
    nix_installed: "{% if nix_stat.stat.exists %}True{% else %}False{% endif %}"

- stat:
    path: ~/.local/bin/pipx
  register: pipx_stat

- name: check if nix is installed
  set_fact:
    pipx_installed: "{% if pipx_stat.stat.exists %}True{% else %}False{% endif %}"

- name: debian | update apt cache
  apt:
    update_cache: true
  become: true
  when: ansible_os_family == 'Debian'

- name: alpine | update apk cache
  apk:
    update_cache: true
  become: true
  when: ansible_os_family == 'Alpine'

- name: nix | update nix cache
  nix:
    update_cache: true
  when: nix_installed
