# vim:ft=ansible
---
- name: add i3 repo
  apt_repository:
    repo='deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe'
  become: yes

- name: install keyring
  command: apt-get --allow-unauthenticated install sur5r-keyring
  become: yes

- name: install deps
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - compton
    - dunst
    - feh
    - i3
    - i3-wm
    - i3lock
    - i3status
    - python3
    - python3-dev
    - rofi
    - xautolock
  become: yes

- name: remove files
  file:
    path={{ item }}
    state=absent
  with_items:
    - ~/.config/dunst
    - ~/.config/rofi
    - ~/.i3
    - ~/.i3status.conf
    - ~/.local/rofi

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.config
    - ~/.config/dunst
    - ~/.config/rofi
    - ~/.i3
    - ~/.local
    - ~/.local/rofi
    - ~/src

- name: create virtualenv
  pip:
    name: "{{ item }}"
    virtualenv: /opt/i3
    virtualenv_command: /usr/bin/python3 -m venv
  become: yes
  with_items:
    - basiciw
    - colour
    - i3pystatus
    - netifaces
    - psutil

- name: link files
  file:
    src={{ batcave_path }}/roles/i3/files/{{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - {'src': 'compton.conf', 'dest': '~/.i3/compton.conf'}
    - {'src': 'config', 'dest': '~/.i3/config'}
    - {'src': 'dunstrc', 'dest': '~/.config/dunst/dunstrc'}
    - {'src': 'i3status.conf', 'dest': '~/.i3/i3status.conf'}
    - {'src': 'i3status.py', 'dest': '~/.i3/i3status.py'}
    - {'src': 'rofi_config.conf', 'dest': '~/.config/rofi/config'}
    - {'src': 'rofi_local.conf', 'dest': '~/.local/rofi/config'}
    - {'src': 'wallpaper.png', 'dest': '~/.i3/wallpaper.png'}
