# vim:ft=ansible
---
- name: create temp dir
  file:
    path: /tmp/i3
    state: directory

- name: get keyring
  command: /usr/lib/apt/apt-helper download-file http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2018.01.30_all.deb keyring.deb SHA256:baa43dbbd7232ea2b5444cae238d53bebb9d34601cc000e82f11111b1889078a
  args:
    chdir: /tmp/i3
    creates: /tmp/i3/keyring.deb
  become: yes

- name: install keyring
  apt:
    deb: /tmp/i3/keyring.deb
  become: yes

- name: add repo
  apt_repository:
    repo='deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe'
  become: yes

- name: install deps
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - dunst
    - feh
    - i3
    - i3-wm
    - i3lock
    - i3status
    - rofi
    - xautolock
  become: yes
  tags:
    - skip_ansible_lint

- name: remove files
  file:
    path={{ item }}
    state=absent
  with_items:
    - ~/.config/dunst
    - ~/.config/rofi
    - ~/.i3
    - ~/.i3status.conf
    - ~/.local/rofi

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.config
    - ~/.config/dunst
    - ~/.config/rofi
    - ~/.i3
    - ~/.local
    - ~/.local/rofi
    - ~/src

- name: link files
  file:
    src={{ batcave_path }}/roles/i3/files/{{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - {'src': 'config', 'dest': '~/.i3/config'}
    - {'src': 'dunstrc', 'dest': '~/.config/dunst/dunstrc'}
    - {'src': 'i3status.conf', 'dest': '~/.i3/i3status.conf'}
    - {'src': 'rofi_config.conf', 'dest': '~/.config/rofi/config'}
    - {'src': 'rofi_local.conf', 'dest': '~/.local/rofi/config'}
    - {'src': 'wallpaper.png', 'dest': '~/.i3/wallpaper.png'}

- name: remove temp dir
  file:
    path: /tmp/i3
    state: absent
