---
- name: add i3 repo
  apt_repository:
    repo='deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe'
  become: yes

- name: super-ugly hack to allow unauthenticated packages to install
  copy:
    content='APT::Get::AllowUnauthenticated "true";'
    dest=/etc/apt/apt.conf.d/99temp
    owner=root
    group=root
    mode=0644
  become: yes

- name: install i3 apt key
  apt:
    name=sur5r-keyring
  become: yes

- name: install deps
  apt:
    name={{ item }}
    state=latest
  with_items:
    - i3
    - feh
    - xautolock
  become: yes

- name: remove hack that allows unauthenticated packages to install
  file:
    path=/etc/apt/apt.conf.d/99temp
    state=absent
  become: yes

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.i3
    - ~/.local
    - ~/.local/bin

- name: copy files
  copy:
    src={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - {'src': 'config', 'dest': '~/.i3/config'}
    - {'src': 'i3status.conf', 'dest': '~/.i3status.conf'}
    - {'src': 'wallpaper.png', 'dest': '~/.i3/wallpaper.png'}
