---
- name: add i3 repo
  apt_repository:
    repo='deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe'
  sudo: yes
  tags:
    - x11

- name: super-ugly hack to allow unauthenticated packages to install
  copy:
    content='APT::Get::AllowUnauthenticated "true";'
    dest=/etc/apt/apt.conf.d/99temp
    owner=root
    group=root
    mode=0644
  sudo: yes
  tags:
    - x11

- name: install i3 apt key
  apt:
    name=sur5r-keyring
  sudo: yes
  tags:
    - x11

- name: install deps
  apt:
    name={{ item }}
    state=latest
  with_items:
    - i3
    - imagemagick
    - scrot
    - xautolock
  sudo: yes
  tags:
    - x11

- name: remove hack that allows unauthenticated packages to install
  file:
    path=/etc/apt/apt.conf.d/99temp
    state=absent
  sudo: yes
  tags:
    - x11

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.i3
    - ~/.local
    - ~/.local/bin
  tags:
    - x11

- name: copy files
  copy:
    src={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - {'src': 'config', 'dest': '~/.i3/config'}
    - {'src': 'i3status.conf', 'dest': '~/.i3status.conf'}
  tags:
    - x11

- name: copy lock script
  copy:
    src=lock.sh
    dest=~/.local/bin/lock.sh
    mode=755
  tags:
    - x11
