# vim:ft=ansible
---
- name: remove i3
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  become: yes
  with_items:
    - i3
    - i3-wm

- name: install deps
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - autoconf
    - automake
    - compton
    - feh
    - i3lock
    - i3status
    - libev-dev
    - libpango1.0-dev
    - libstartup-notification0-dev
    - libxcb-cursor-dev
    - libxcb-icccm4-dev
    - libxcb-keysyms1-dev
    - libxcb-randr0-dev
    - libxcb-util0-dev
    - libxcb-xinerama0-dev
    - libxcb-xkb-dev
    - libxcb-xrm-dev
    - libxcb-xrm0
    - libxcb1-dev
    - libxkbcommon-dev
    - libxkbcommon-x11-dev
    - libyajl-dev
    - rofi
    - xautolock
  become: yes

- name: remove files
  file:
    path={{ item }}
    state=absent
  with_items:
    - ~/.i3
    - ~/.i3status.conf
    - ~/.local/rofi

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.i3
    - ~/.local
    - ~/.local/rofi
    - ~/src

- name: clone i3-gaps
  git:
    repo: https://github.com/Airblader/i3
    dest: ~/src/i3-gaps

- name: prepare build
  command: "{{ item }}"
  args:
    chdir: ~/src/i3-gaps
  with_items:
    - autoreconf --force --install
    - rm -rf build/
    - mkdir -p build

- name: build
  command: "{{ item }}"
  args:
    chdir: ~/src/i3-gaps/build
  with_items:
    - ../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
    - make

- name: install
  command: make install
  args:
    chdir: /home/{{ ansible_user_id }}/src/i3-gaps/build
  become: yes

- name: link files
  file:
    src={{ batcave_path }}/roles/i3/files/{{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - {'src': 'config', 'dest': '~/.i3/config'}
    - {'src': 'i3status.conf', 'dest': '~/.i3/i3status.conf'}
    - {'src': 'wallpaper.png', 'dest': '~/.i3/wallpaper.png'}
    - {'src': 'compton.conf', 'dest': '~/.i3/compton.conf'}
    - {'src': 'rofi.conf', 'dest': '~/.local/rofi/config'}
