---
- name: debian | install deps
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - adwaita-qt
    - adwaita-icon-theme-full
    - fonts-symbola
  become: true
  when: ansible_os_family == 'Debian'

- name: alpine | install deps
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - adwaita-gtk2-theme
    - adwaita-icon-theme
  become: true
  when: ansible_os_family == 'Alpine'

- name: needed dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.config
    - ~/.config/fontconfig
    - ~/.config/gtk-3.0
    - ~/.fonts
    - ~/.themes

- name: rebuild font cache
  command: fc-cache -r ~/.fonts
