# vim:ft=ansible
---
- name: install deps
  apt:
    name: "{{ item }}"
  become: true
  with_items:
    - cmake
    - cmake-data
    - i3-wm
    - libasound2-dev
    - libcairo2-dev
    - libcurl4-openssl-dev
    - libiw-dev
    - libjsoncpp-dev
    - libmpdclient-dev
    - libnl-3-dev
    - libpulse-dev
    - libxcb-cursor-dev
    - libxcb-ewmh-dev
    - libxcb-icccm4-dev
    - libxcb-image0-dev
    - libxcb-randr0-dev
    - libxcb-util0-dev
    - libxcb-xkb-dev
    - libxcb-xrm-dev
    - libxcb1-dev
    - pkg-config
    - python-xcbgen
    - xcb-proto
    - xcb-proto

- name: needed dirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config
    - ~/.config/polybar
    - ~/.local
    - ~/src

- name: get code
  git:
    repo: https://github.com/jaagr/polybar
    dest: ~/src/polybar
    recursive: true
  tags:
    - skip_ansible_lint

- name: create build dir
  file:
    path: ~/src/polybar/build
    state: directory

- name: compile
  command: cmake -DCMAKE_INSTALL_PREFIX=~/.local ..
  args:
    chdir: ~/src/polybar/build
    creates: ~/src/polybar/build/Makefile

- name: install
  command: make install
  args:
    chdir: /home/{{ ansible_user_id }}/src/polybar/build
    creates: ~/.local/bin/polybar

- name: link files
  file:
    src: "{{ batcave_path }}/roles/polybar/files/{{ item }}"
    dest: "~/.config/polybar/{{ item }}"
    state: link
  with_items:
    - config
    - launch.sh
