# vim:ft=ansible
---
- name: add ppa
  apt_repository:
    repo: 'ppa:fish-shell/release-3'
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: install deps
  package:
    state: latest
    name:
      - fish
  become: yes
  tags:
    - skip_ansible_lint

- name: install deps debian
  apt:
    state: latest
    name:
      - curl
      - ncurses-base
      - procps
  become: yes
  when: ansible_os_family == 'Debian'

- name: install deps alpine
  apk:
    state: latest
    name:
      - bc
      - mdocml-apropos
      - ncurses
      - util-linux
  become: yes
  when: ansible_os_family == 'Alpine'

- name: install addons
  command: /usr/bin/fish -c 'fisher add {{ item }}'
  with_items:
    - oh-my-fish/theme-bobthefish
    - edc/bass
