# vim:ft=ansible
---
- name: install deps
  package:
    name=tmux
    state=present
  become: yes

- name: remove files
  file:
    path=~/.tmux.conf
    state=absent
  with_items:
    - ~/.tmux.conf
    - ~/.tmuxp

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.local
    - ~/.local/bin
    - ~/.tmuxp

- name: check if pipsi installed
  stat:
    path: ~/.local/bin/pipsi
  register: pipsi_result

- name: install tmuxp
  command: ~/.local/bin/pipsi install tmuxp
  args:
    creates: ~/.local/venvs/tmuxp/bin/tmuxp
  when: pipsi_result.stat.exists == True

- name: install xpanes
  get_url:
    url: https://raw.githubusercontent.com/greymd/tmux-xpanes/master/bin/xpanes
    dest: ~/.local/bin/tmux-xpanes
    mode: 0755

- name: link files
  file:
    src={{ batcave_path }}/roles/tmux/files/{{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - { 'src': 'tmux.conf', 'dest': '~/.tmux.conf' }
    - { 'src': 'communications.yml', 'dest': '~/.tmuxp/communications.yml' }
    - { 'src': 'code.yml', 'dest': '~/.tmuxp/code.yml' }
