---
- name: install deps
  apt:
    name=tmux
    state=present
  become: yes
  when: ansible_os_family == 'Debian'

- name: install deps
  apk:
    name=tmux
    state=present
  become: yes
  when: ansible_os_family == 'Alpine'

- name: remove tmux config
  file:
    path=~/.tmux.conf
    state=absent

- name: link tmux config
  file:
    src={{ role_path }}/files/tmux.conf
    dest=~/.tmux.conf
    state=link
