---
- name: install deps
  apt:
    name=tmux
    state=present
  become: yes
  when: ansible_os_family == 'Debian'

- name: install deps
  apk:
    name=tmux
    state=present
  become: yes
  when: ansible_os_family == 'Alpine'

- name: copy tmux config
  copy:
    src=tmux.conf
    dest=~/.tmux.conf
