---
- name: install deps
  package:
    name=tmux
    state=present
  become: yes
  when: ansible_os_family == 'Debian'

- name: remove tmux config
  file:
    path=~/.tmux.conf
    state=absent

- name: link tmux config
  file:
    src={{ batcave_path }}/roles/tmux/files/tmux.conf
    dest=~/.tmux.conf
    state=link
