---
- include_vars : "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"

- name: install deps
  package:
    name={{ item }}
    state=present
  become: yes
  with_items:
    - "{{ python3_package_name }}"
    - "{{ pip3_package_name }}"

- name: get installed python3 version
  shell: python3 --version
  register: python3_version

- set_fact:
    python3_compatible: "{% if '3.4' in python3_version.stdout or '3.5' in python3_version.stdout %}yes{% else %}no{% endif %}"

- name: install python packages
  pip:
    name={{ item }}
    executable=pip3
    state=latest
  become: yes
  with_items:
    - prompt_toolkit
    - pygments
    - xonsh
    - xonsh-apt_tabcomplete
    - xonsh-autoxsh
    - xonsh-docker_tabcomplete
    - xonsh-vox_tabcomplete
  when: python3_compatible

- name: link files
  file:
    src={{ batcave_path }}/roles/xonsh/files/{{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - { 'src': 'xonshrc', 'dest': '~/.xonshrc' }
  when: python3_compatible

- name: add lines to .profile
  lineinfile:
    dest=~/.profile
    state=present
    create=yes
    line={{ item }}
  with_items:
    - '[ -f /usr/local/bin/xonsh ] && exec /usr/local/bin/xonsh'
    - '[ -f /usr/bin/xonsh ] && exec /usr/bin/xonsh'
  when: python3_compatible
