# vim:ft=ansible
---
- name: include vars
  include_vars : "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"

- name: install deps
  package:
    name={{ item }}
    state=present
  become: yes
  with_items:
    - '{{ python3_package_name }}'
    - '{{ shell_package_name }}'

- name: check local pip path
  stat: path=~/.local/bin/pip
  register: pip

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.local
    - ~/.local/bin

- name: set sh as default shell
  user:
    name={{ ansible_env.USER }}
    shell=/bin/sh
  become: yes
  when: ansible_os_family == 'Debian'

- name: install python packages
  pip:
    name: "{{ item }}"
    virtualenv: /opt/xonsh
    virtualenv_command: /usr/bin/python3 -m venv
    state: latest
  become: yes
  with_items:
    - distro
    - prompt-toolkit
    - pygments
    - pygments-style-solarized
    - xonsh
    - xonsh-apt_tabcomplete
    - xonsh-vox_tabcomplete
    - xontrib-powerline
  tags:
    - skip_ansible_lint

- name: link files
  file:
    src={{ batcave_path }}/roles/xonsh/files/{{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - { 'src': 'xonshrc', 'dest': '~/.xonshrc' }
    - { 'src': 'xonsh', 'dest': '~/.local/bin/xonsh' }

- name: export PATH
  lineinfile:
    path: ~/.profile
    line: 'export PATH="{{ item }}:$PATH"'
  with_items:
    - $HOME/.local/bin
