# vim:ft=ansible
---
- name: install deps
  apt:
    name={{ item }}
    state=present
  become: yes
  with_items:
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils

- name: install pyenv
  git:
    repo=https://github.com/yyuu/pyenv.git
    dest=~/.pyenv
