---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
  when: vim_package_name is not defined

- name: install deps
  package:
    name={{ item }}
    state=latest
  with_items:
    - "{{ vim_package_name }}"
  become: yes

- name: remove files
  file:
    path={{ item }}
    state=absent
  with_items:
    - ~/.vimrc
    - ~/.vim

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.vim
    - ~/.vim/autoload
    - ~/.vim/colors
    - ~/.vim/plugged
    - ~/.vim/spell

- name: link files
  file:
    src={{ batcave_path }}/roles/vim/files/{{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - {'src': 'vimrc', 'dest': '~/.vimrc'}

- name: get some files
  get_url:
    url={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - {'src': 'http://ftp.vim.org/pub/vim/runtime/spell/de.utf-8.spl', 'dest': '~/.vim/spell/de.utf-8.spl'}
    - {'src': 'http://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.spl', 'dest': '~/.vim/spell/en.utf-8.spl'}
    - {'src': 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', 'dest': '~/.vim/autoload/plug.vim'}
    - {'src': 'https://raw.githubusercontent.com/tomasr/molokai/master/colors/molokai.vim', 'dest': '~/.vim/colors/molokai.vim'}

- name: install plugins
  command: vim +PlugInstall +qall
