# vim:ft=ansible
---
- name: install deps for debian
  package:
    name={{ item }}
    state=latest
  with_items:
    - python
    - python-virtualenv
    - python3
    - python3-venv
  become: yes
  when: ansible_os_family == 'Debian'

- name: install neovim through brew
  homebrew:
    name: neovim
    state: latest
  when: ansible_os_family == 'Debian'

- name: install deps for alpine
  package:
    name={{ item }}
    state=latest
  with_items:
    - gcc
    - musl-dev
    - neovim
    - py2-virtualenv
    - python2
    - python2-dev
    - python3
    - python3-dev
  become: yes
  when: ansible_os_family == 'Alpine'

- name: remove files
  file:
    path={{ item }}
    state=absent
  with_items:
    - /home/{{ ansible_user_id }}/.vimrc
    - /home/{{ ansible_user_id }}/.vim
    - /home/{{ ansible_user_id }}/.config/nvim
  become: yes

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.vim
    - ~/.vim/autoload
    - ~/.vim/colors
    - ~/.vim/plugged
    - ~/.vim/spell
    - ~/.vim/thesaurus
    - ~/.config

- name: link files
  file:
    src={{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - {'src': '{{ batcave_path }}/roles/vim/files/vimrc', 'dest': '~/.vimrc'}
    - {'src': '~/.vim', 'dest': '~/.config/nvim'}
    - {'src': '~/.vimrc', 'dest': '~/.config/nvim/init.vim'}

- name: get some files
  get_url:
    url={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - {'src': 'http://ftp.vim.org/pub/vim/runtime/spell/de.utf-8.spl', 'dest': '~/.vim/spell/de.utf-8.spl'}
    - {'src': 'http://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.spl', 'dest': '~/.vim/spell/en.utf-8.spl'}
    - {'src': 'https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim', 'dest': '~/.vim/colors/solarized.vim'}
    - {'src': 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', 'dest': '~/.vim/autoload/plug.vim'}
    - {'src': 'https://raw.githubusercontent.com/sjl/badwolf/master/colors/badwolf.vim', 'dest': '~/.vim/colors/badwolf.vim'}
    - {'src': 'https://raw.githubusercontent.com/tlhr/anderson.vim/master/colors/anderson.vim', 'dest': '~/.vim/colors/anderson.vim'}
    - {'src': 'https://raw.githubusercontent.com/lifepillar/vim-solarized8/master/colors/solarized8_dark_flat.vim', 'dest': '~/.vim/colors/solarized8_dark_flat.vim'}
    - {'src': 'https://raw.githubusercontent.com/lifepillar/vim-solarized8/master/colors/solarized8_flat.vim', 'dest': '~/.vim/colors/solarized8_flat.vim'}
    - {'src': 'https://raw.githubusercontent.com/lifepillar/vim-solarized8/master/colors/solarized8.vim', 'dest': '~/.vim/colors/solarized8.vim'}

- name: create neovim virtualenv for python2
  pip:
    name: "{{ item }}"
    virtualenv: /opt/neovim2
  with_items:
    - neovim
  become: yes

- name: create neovim virtualenv for python3
  pip:
    name: "{{ item }}"
    virtualenv: /opt/neovim3
    virtualenv_command: /usr/bin/python3 -m venv
  with_items:
    - neovim
  become: yes

- name: install plugins
  command: nvim +PlugInstall +qall

