---
- name: install deps
  apt:
    name={{ item }}
    state=latest
  with_items:
    - vim
    - vim-nox
  become: yes
  when: ansible_os_family == 'Debian'

- name: install deps
  apk:
    name={{ item }}
    state=latest
  with_items:
    - vim
  become: yes
  when: ansible_os_family == 'Alpine'

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.vim
    - ~/.vim/bundle
    - ~/.vim/autoload
    - ~/.vim/autoload/ftplugin

- name: copy files
  copy:
    src={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - {'src': 'vimrc', 'dest': '~/.vimrc'}
    - {'src': 'html.vim', 'dest': '~/.vim/autoload/ftplugin/html.vim'}
    - {'src': 'python.vim', 'dest': '~/.vim/autoload/ftplugin/python.vim'}

- name: clone Vundle repo
  git:
    repo=https://github.com/gmarik/Vundle.vim.git
    dest=~/.vim/bundle/Vundle.vim
