---
- name: add neovim repo
  apt_repository:
    repo=ppa:neovim-ppa/unstable
    state=present
  sudo: yes

- name: install deps
  apt:
    name={{ item }}
    state=latest
  with_items:
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
    - vim
    - neovim
  sudo: yes

- name: install neovim python package
  pip:
    name=neovim
    state=latest
  sudo: yes

- name: needed dirs
  file:
    path=~/.vim
    state=directory
  with_items:
    - ~/.vim
    - ~/.vim/bundle

- name: copy files
  copy:
    src={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - {'src': 'vimrc', 'dest': '~/.vimrc'}
    - {'src': 'html.vim', 'dest': '~/.vim/html.vim'}
    - {'src': 'python.vim', 'dest': '~/.vim/python.vim'}

- name: nvimrc symlink
  file:
    src=~/.vimrc
    dest=~/.nvimrc
    state=link

- name: clone Vundle repo
  git:
    repo=https://github.com/gmarik/Vundle.vim.git
    dest=~/.vim/bundle/Vundle.vim
