# vim:ft=ansible
---
- name: add ppa
  apt_repository:
    repo: 'ppa:neovim-ppa/stable'
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: install deps
  package:
    name={{ item }}
    state=latest
  with_items:
    - neovim
  become: yes

- name: remove files
  file:
    path={{ item }}
    state=absent
  with_items:
    - /home/{{ ansible_user_id }}/.vimrc
    - /home/{{ ansible_user_id }}/.vim
    - /home/{{ ansible_user_id }}/.config/nvim
  become: yes

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.vim
    - ~/.vim/autoload
    - ~/.vim/colors
    - ~/.vim/plugged
    - ~/.vim/spell
    - ~/.vim/thesaurus
    - ~/.config

- name: link files
  file:
    src={{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - {'src': '{{ batcave_path }}/roles/vim/files/vimrc', 'dest': '~/.vimrc'}
    - {'src': '~/.vim', 'dest': '~/.config/nvim'}
    - {'src': '~/.vimrc', 'dest': '~/.config/nvim/init.vim'}

- name: get some files
  get_url:
    url={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - {'src': 'http://ftp.vim.org/pub/vim/runtime/spell/de.utf-8.spl', 'dest': '~/.vim/spell/de.utf-8.spl'}
    - {'src': 'http://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.spl', 'dest': '~/.vim/spell/en.utf-8.spl'}
    - {'src': 'https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim', 'dest': '~/.vim/colors/solarized.vim'}
    - {'src': 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', 'dest': '~/.vim/autoload/plug.vim'}
    - {'src': 'https://raw.githubusercontent.com/sjl/badwolf/master/colors/badwolf.vim', 'dest': '~/.vim/colors/badwolf.vim'}
    - {'src': 'https://raw.githubusercontent.com/tlhr/anderson.vim/master/colors/anderson.vim', 'dest': '~/.vim/colors/anderson.vim'}
    - {'src': 'https://www.openthesaurus.de/export/OpenThesaurus-Textversion.zip', 'dest': '/tmp/thesaurus.zip'}

- name: get thesaurus
  unarchive:
    src : https://www.openthesaurus.de/export/OpenThesaurus-Textversion.zip
    dest: ~/.vim/thesaurus/
    remote_src: True

- name: install plugins
  command: nvim +PlugInstall +qall

