---
- name: install deps
  apt:
    name={{ item }}
    state=latest
  with_items:
    - vim-nox
  become: yes
  when: ansible_os_family == 'Debian'

- name: install deps
  apk:
    name={{ item }}
    state=latest
  with_items:
    - vim
  become: yes
  when: ansible_os_family == 'Alpine'

- name: needed dirs
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.vim
    - ~/.vim/plugged
    - ~/.vim/autoload
    - ~/.vim/spell

- name: remove files
  file:
    path={{ item }}
    state=absent
  with_items:
    - ~/.vimrc
    - ~/.vim/autoload/ftplugin/html.vim
    - ~/.vim/autoload/ftplugin/python.vim

- name: link files
  file:
    src={{ batcave_path }}/roles/vim/files/{{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - {'src': 'vimrc', 'dest': '~/.vimrc'}

- name: get spell files
  get_url:
    url={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - {'src': 'http://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.spl', 'dest': '~/.vim/spell/en.utf-8.spl'}
    - {'src': 'http://ftp.vim.org/pub/vim/runtime/spell/de.utf-8.spl', 'dest': '~/.vim/spell/de.utf-8.spl'}

- name: get vim-plug
  get_url:
    url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest=~/.vim/autoload/plug.vim

- name: clone some plugins
  git:
    repo={{ item.repo }}
    dest={{ item.dest }}
  with_items:
    - {'repo': 'https://github.com/altercation/vim-colors-solarized.git', 'dest': '~/.vim/plugged/vim-colors-solarized'}

- name: update plugins
  command: vim +PlugUpdate +qall

- name: install plugins
  command: vim +PlugInstall +qall
