---
- name: install deps
  apt:
    name={{ item }}
    state=latest
  with_items:
    - vim
    - vim-nox
  sudo: yes

- name: needed dirs
  file:
    path=~/.vim
    state=directory
  with_items:
    - ~/.vim
    - ~/.vim/bundle

- name: copy files
  copy:
    src={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - {'src': 'vimrc', 'dest': '~/.vimrc'}
    - {'src': 'html.vim', 'dest': '~/.vim/html.vim'}
    - {'src': 'python.vim', 'dest': '~/.vim/python.vim'}

- name: clone Vundle repo
  git:
    repo=https://github.com/gmarik/Vundle.vim.git
    dest=~/.vim/bundle/Vundle.vim
