---
- name: add ppa
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: install deps for debian
  package:
    state: latest
    name:
      - neovim
      - python
      - python-virtualenv
      - python3
      - python3-venv
      - shellcheck
  become: true
  when: ansible_os_family == 'Debian'
  tags:
    - skip_ansible_lint

- name: install deps for alpine
  package:
    state: latest
    name:
      - gcc
      - musl-dev
      - neovim
      - py2-virtualenv
      - python2
      - python2-dev
      - python3
      - python3-dev
  become: true
  when: ansible_os_family == 'Alpine'
  tags:
    - skip_ansible_lint

- name: create neovim virtualenv for python2
  pip:
    name:
      - neovim
    virtualenv: /opt/neovim2
    state: latest
  become: true

- name: create neovim virtualenv for python3
  pip:
    name:
      - jedi
      - neovim
      - pynvim
    virtualenv: /opt/neovim3
    virtualenv_command: /usr/bin/python3 -m venv
    state: latest
  become: true

- name: install plugins
  command: nvim +PlugInstall +qall
  tags:
    - skip_ansible_lint

- name: needed python packages
  pipx:
    name: "{{ item }}"
    state: latest
  loop:
    - ansible-lint
    - python-language-server
    - yamllint
  when: pipx_installed

- name: needed nix packages
  nix:
    name: "{{ item }}"
    state: latest
  loop:
    - LanguageTool
  when: nix_installed
